import { StyleSheet } from "react-native";

import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  filterContainer: {
    paddingHorizontal: 20,
    marginTop: 4,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  viewAll: {
    color: Colors.mrDBlue,
    fontSize: 14,
    fontWeight: "500",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.softGrey,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: Colors.darkCharcoalGrey,
    letterSpacing: -0.5,
  },
  resetBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: Colors.skyBlue,
  },
  resetBtnText: {
    color: Colors.mrDBlue,
    fontSize: 14,
    fontWeight: "600",
  },
  contentSection: {
    flexDirection: "column",
    gap: 12,
    paddingTop: 8,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: Colors.softGrey,
    marginHorizontal: 20,
    marginVertical: 8,
  },
  contentTitle: {
    fontWeight: "600",
    fontSize: 16,
    color: Colors.darkCharcoalGrey,
    marginBottom: 4,
    letterSpacing: -0.3,
  },
  chipFlatlist: {
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  chipBtn: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: Colors.lightGrey,
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  chipBtnSelected: {
    borderColor: Colors.mrDBlue,
    shadowColor: Colors.mrDBlue,
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  chipText: {
    fontSize: 14,
    fontWeight: "500",
  },
  fuelCheckbox: {
    paddingTop: 5,
    paddingHorizontal: 20,
  },
  fuelOptions: {
    flexDirection: "row",
    paddingTop: 12,
    paddingBottom: 4,
    flexWrap: "wrap",
    gap: 12,
  },
  checkbox: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: Colors.lightGrey,
    backgroundColor: Colors.white,
  },
  checkboxSelected: {
    borderColor: Colors.mrDBlue,
    backgroundColor: Colors.skyBlue,
  },
  box: {
    width: 20,
    height: 20,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    backgroundColor: "transparent",
    borderWidth: 1.5,
  },
  checkboxText: {
    fontSize: 14,
    fontWeight: "500",
  },
  priceInputContainer: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    backgroundColor: Colors.white,
  },
  priceInputRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 12,
  },
  fieldsetWrapper: {
    flex: 1,
  },
  fieldsetLabel: {
    marginBottom: 8,
    marginLeft: 4,
  },
  fieldsetLabelText: {
    fontSize: 14,
    fontWeight: "600",
    color: Colors.darkCharcoalGrey,
    letterSpacing: 0.2,
  },
  fieldsetInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bg,
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 52,
    borderWidth: 1,
    borderColor: Colors.lightGrey,
  },
  fieldsetInputFocused: {
    borderColor: Colors.mrDBlue,
    backgroundColor: Colors.white,
    shadowColor: Colors.mrDBlue,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  currencyPrefix: {
    fontSize: 15,
    fontWeight: "600",
    color: Colors.darkCharcoalGrey,
    marginRight: 8,
  },
  fieldsetInput: {
    flex: 1,
    fontSize: 15,
    color: Colors.darkCharcoalGrey,
    backgroundColor: "transparent",
  },
  footer: {
    marginTop: 12,
    marginBottom: 24,
    paddingHorizontal: 20,
    gap: 12,
  },
  footerBtn: {
    backgroundColor: Colors.mrDBlue,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: Colors.mrDBlue,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 2,
  },
  footerText: {
    color: Colors.white,
    fontWeight: "600",
    fontSize: 16,
    letterSpacing: -0.3,
  },
});
