import { StyleSheet } from "react-native";
import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    overflow: "hidden",
    elevation: 2,
    shadowColor: Colors.darkCharcoalGrey,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
  },
  imageContainer: {
    width: "100%",
    height: 240,
    position: "relative",
  },
  image: {
    width: "100%",
    height: "100%",
  },
  ratingBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 4,
  },
  ratingText: {
    color: Colors.white,
    fontSize: 13,
    fontWeight: "600",
  },
  saleBadge: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.lightRed,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 4,
  },
  saleBadgeText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  typeContainer: {
    position: "absolute",
    bottom: 12,
    left: 12,
  },
  typeBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  typeBadgeText: {
    fontSize: 12,
    fontWeight: "600",
  },
  contentSection: {
    padding: 16,
  },
  headerRow: {
    marginBottom: 10,
  },
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  vehicleName: {
    fontSize: 20,
    fontWeight: "600",
    color: Colors.darkCharcoalGrey,
    flex: 1,
  },
  yearText: {
    fontSize: 14,
    fontWeight: "500",
    color: Colors.mediumGrey,
    marginLeft: 8,
  },
  detailsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  detailBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.bg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 4,
  },
  detailText: {
    fontSize: 12,
    color: Colors.mediumGrey,
    fontWeight: "500",
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 14,
  },
  locationText: {
    fontSize: 13,
    color: Colors.mediumGrey,
    flex: 1,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: Colors.bg,
  },
  priceContainer: {
    flex: 1,
  },
  priceValue: {
    fontSize: 24,
    fontWeight: "600",
    color: Colors.lightGreen,
    marginBottom: 2,
  },
  priceLabel: {
    fontSize: 12,
    color: Colors.mediumGrey,
    fontWeight: "500",
  },
  ctaButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: Colors.mrDBlue,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    gap: 6,
    elevation: 2,
    shadowColor: Colors.mrDBlue,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  ctaText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: "600",
  },
});
