import { StyleSheet } from "react-native";

import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 2,
  },
  imageContainer: {
    position: "relative",
    width: "100%",
    height: 200,
    backgroundColor: Colors.softGrey,
  },
  image: {
    width: "100%",
    height: "100%",
  },
  typeContainer: {
    position: "absolute",
    top: 16,
    left: 16,
  },
  typeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.white,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  typeBadgeText: {
    fontSize: 12,
    fontWeight: 600,
  },
  assignedBadge: {
    position: "absolute",
    top: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.lightYellow,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  assignedText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: 600,
  },
  contentSection: {
    padding: 18,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  titleContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  vehicleName: {
    fontSize: 20,
    fontWeight: 600,
    color: Colors.darkCharcoalGrey,
    flex: 1,
  },
  yearText: {
    fontSize: 15,
    fontWeight: 600,
    color: Colors.mediumGrey,
  },
  detailsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  detailBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.bg,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
  },
  detailText: {
    fontSize: 12,
    color: Colors.mediumGrey,
    fontWeight: 500,
  },
  footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.softGrey,
  },
  priceContainer: {
    flexDirection: "column",
  },
  priceValue: {
    fontSize: 24,
    fontWeight: 600,
    color: Colors.mrDBlue,
    lineHeight: 28,
  },
  priceLabel: {
    fontSize: 13,
    color: Colors.mediumGrey,
    fontWeight: 500,
    marginTop: 2,
  },
  selectButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: Colors.emeraldGreen,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 24,
    shadowColor: Colors.emeraldGreen,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 2,
  },
  selectText: {
    color: Colors.white,
    fontSize: 14,
    fontWeight: 600,
  },
});
