export const Colors = {
  tintColorLight: '#2f95dc',
  tintColorDark: '#fff',
  black: '#000',
  darkCharcoal: '#333',
  white: '#fff',
  grey: '#ccc',
  darkGrey: '#a9a9a9',
  mediumGrey: '#747C7C',
  midToneGrey: '#B0B0B0',
  lightGrey: '#D9D9D9',
  whiteSmoke: '#ECECEC',
  lighterGrey: '#D7D7D7',
  softGrey: '#EDEDED',
  mediumDarkGrey: '#424242',
  slateGray: '#4f5e7b',
  bg: '#FAF9F6',
  skyLight: '#EFF2FC',
  yellow: '#FFD854',
  darkGreen: '#306C3D',
  emeraldGreen: '#22C55E',
  lightBlue: 'rgba(49, 173, 212, 0.28)',
  lighterBlue: '#EFF2FC',
  skyBlue: 'rgba(49, 173, 212, 0.03)',
  tealLight: '#31ADD408',
  charcoalGray: '#424242',
  darkBlue: '#1b1a57',
  primaryBlue: '#5669FF',
  verylightBlue: '#eff2f6',
  grayishRed: '#3b3a3a',
  greyLighter: "#E6E6E6",
  veryDarkGrey: "#222",
  dimGrey: "#444",
  mediumLightGrey: "#9CA6A6",
  indigoBlue: "#656ABB",
  starGrey: "#dfd7bc",
  mediumGreen: "#4CAF50",
  purplePink: "#C635DC",
  lightRed: '#EB634B',
  lightYellow: '#FACC15',
  lightGreen: '#22C55E',
  charcoalBlue: "#1A1F36"
};

export default {
  light: {
    text: Colors.black,
    background: Colors.white,
    tint: Colors.tintColorLight,
    tabIconDefault: Colors.grey,
    tabIconSelected: Colors.tintColorLight,
  },
  dark: {
    text: Colors.white,
    background: Colors.black,
    tint: Colors.tintColorDark,
    tabIconDefault: Colors.grey,
    tabIconSelected: Colors.tintColorDark,
  },
};
