import { StyleSheet } from "react-native";

import { Colors } from "@/constants/ui";

export const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.white,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 16,
    position: "relative",
  },
  body: {
    padding: 20,
    paddingBottom: 16,
    flexDirection: "row",
    gap: 16,
  },
  image: {
    width: 120,
    height: 120,
    backgroundColor: Colors.verylightBlue,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 2,
  },
  imagePlaceholder: {
    width: 120,
    height: 120,
    backgroundColor: Colors.skyLight,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  optionsBtnWrapper: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 10,
    backgroundColor: Colors.white,
    borderRadius: 18,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  optionsBtn: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  payments: {
    paddingHorizontal: 20,
    paddingBottom: 16,
    gap: 12,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  paymentCard: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: Colors.bg,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.04)",
  },
  paymentText: {
    color: Colors.mediumGrey,
    fontSize: 12,
    fontWeight: 500,
    textAlign: "center",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  amountText: {
    textAlign: "center",
    fontWeight: 600,
    fontSize: 17,
    color: Colors.darkCharcoalGrey,
  },
  dateText: {
    textAlign: "center",
    fontWeight: 500,
    fontSize: 12,
    color: Colors.mediumGrey,
  },
  recentPaidWrapper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  name: {
    fontSize: 17,
    fontWeight: 600,
    color: Colors.darkCharcoalGrey,
    lineHeight: 22,
  },
  actionsContainer: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    gap: 12,
  },
  applicantBtnWrapper: {
    position: "relative",
  },
  btnStyles: {
    paddingVertical: 14,
    backgroundColor: Colors.mrDBlue,
    borderRadius: 12,
    shadowColor: Colors.mrDBlue,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  viewDetailsBtn: {
    paddingVertical: 14,
    backgroundColor: Colors.lightGreen,
    borderRadius: 12,
    shadowColor: Colors.lightGreen,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 3,
  },
  btnText: {
    fontSize: 15,
    fontWeight: 600,
    color: Colors.white,
    textAlign: "center",
  },
  details: {
    flexDirection: "column",
    justifyContent: "space-between",
    // flex: 1,
    // paddingVertical: 2,
  },
  detailIcon: {
    width: 18,
    height: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  detailsRow: {
    gap: 6,
    flexDirection: "row",
    alignItems: "center",
  },
  paymentCountText: {
    color: Colors.mediumGrey,
    fontSize: 13,
    fontWeight: 500,
  },
  detailText: {
    color: Colors.mediumGrey,
    fontSize: 14,
    fontWeight: 500,
  },
  unreadBadge: {
    backgroundColor: Colors.lightRed,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    position: "absolute",
    elevation: 3,
    top: 10,
    right: -6,
    shadowColor: Colors.lightRed,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  unreadBadgeText: {
    color: Colors.white,
    fontSize: 11,
    fontWeight: 600,
  },
  interestedBuyersBtn: {
    paddingVertical: 14,
    backgroundColor: Colors.mrDBlue,
    borderRadius: 12,
    shadowColor: Colors.mrDBlue,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 2,
  },
  interestedBuyersBtnText: {
    fontSize: 16,
    fontWeight: 600,
    color: Colors.white,
    textAlign: "center",
  },
  inactiveNotice: {
    marginHorizontal: 20,
    marginBottom: 16,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: "rgba(235, 99, 75, 0.1)",
    borderRadius: 10,
  },
  inactiveNoticeText: {
    fontSize: 13,
    fontWeight: 500,
    color: Colors.lightRed,
    lineHeight: 18,
  },
  activateText: {
    fontWeight: 600,
    color: Colors.lightGreen,
  },
});
