import { StyleSheet } from "react-native";

import { Colors } from "@/constants/ui";
import { topOffset } from "@/src/components/appStyles";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.bg,
    flex: 1,
    ...topOffset,
  },
  mainContainer: {
    paddingHorizontal: 14,
    paddingTop: 12,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0.05)",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.bg,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: "rgba(0, 0, 0, 0.06)",
  },
  header: {
    alignItems: "center",
    paddingHorizontal: 14,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: Colors.darkCharcoalGrey,
    flex: 1,
  },
  tabSwitcherContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
  },
  tabSwitcher: {
    flexDirection: "row",
    backgroundColor: Colors.bg,
    borderRadius: 14,
    padding: 4,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 1,
  },
  tab: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  tabActive: {
    backgroundColor: Colors.white,
    shadowColor: Colors.mrDBlue,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
  },
  tabText: {
    fontSize: 14,
    fontWeight: 600,
    color: Colors.mediumGrey,
  },
  tabTextActive: {
    fontSize: 14,
    fontWeight: 800,
    color: Colors.mrDBlue,
    letterSpacing: 0.3,
  },
  driverCard: {
    flexDirection: "row",
    backgroundColor: Colors.white,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 18,
    margin: 16,
    alignItems: "center",
    shadowColor: Colors.mrDBlue,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    borderWidth: 1,
    borderColor: "rgba(118, 203, 237, 0.1)",
  },
  nameText: {
    color: Colors.darkCharcoalGrey,
    fontSize: 17,
    fontWeight: 800,
    marginLeft: 14,
  },
  addPaymentButton: {
    backgroundColor: Colors.mrDBlue,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    marginHorizontal: 16,
    marginBottom: 18,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: Colors.mrDBlue,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
    flexDirection: "row",
    gap: 10,
  },
  addText: {
    color: Colors.white,
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  listHeader: {
    paddingHorizontal: 18,
    paddingBottom: 14,
    paddingTop: 4,
  },
  listHeaderText: {
    fontSize: 12,
    fontWeight: 800,
    color: Colors.mediumGrey,
    textTransform: "uppercase",
    letterSpacing: 1.2,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: Colors.skyLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: Colors.darkCharcoalGrey,
    marginBottom: 8,
    textAlign: "center",
  },
  emptyStateSubtitle: {
    fontSize: 15,
    color: Colors.mediumGrey,
    textAlign: "center",
    lineHeight: 22,
  },
});
